version: '3.4'

services:
  booleanhooligans:
    image: booleanhooligans
    build:
      context: Transition Test
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8000:8000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
